name: SeecraftPlugin
version: 0.0.5
author: archessmn
main: com.github.archessmn.SeecraftPlugin_v0_0_5.main
api-version: 1.15

commands:
  find:
    description: Finds Spawn or the nearest Haven Checkpoint.

  register:
    description: Registers a new Haven Checkpoint!

  remove:
    description: Removes the checkpoint in that area, use wisely.

  testfind:
    description: Test for the Find command.

  colour:
    description: Changes the colour of your name in chat (please ask admin).


permissions:
  member:
    description: The default role

  mod:
    description: Moderator

  admin:
    description: Admin yay

default-permission: member